// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: challenge_scores.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addChallengeScoreFines = `-- name: AddChallengeScoreFines :one
UPDATE challenge_scores
SET total_fines         = total_fines + $1::numeric,
    updated_at          = NOW()
WHERE user_challenge_id = $2::uuid
RETURNING id, user_challenge_id, total_points, total_fines, last_submission_date, updated_at
`

type AddChallengeScoreFinesParams struct {
	Amount          pgtype.Numeric
	UserChallengeID uuid.UUID
}

func (q *Queries) AddChallengeScoreFines(ctx context.Context, arg AddChallengeScoreFinesParams) (ChallengeScore, error) {
	row := q.db.QueryRow(ctx, addChallengeScoreFines, arg.Amount, arg.UserChallengeID)
	var i ChallengeScore
	err := row.Scan(
		&i.ID,
		&i.UserChallengeID,
		&i.TotalPoints,
		&i.TotalFines,
		&i.LastSubmissionDate,
		&i.UpdatedAt,
	)
	return i, err
}

const addChallengeScorePoints = `-- name: AddChallengeScorePoints :one
UPDATE challenge_scores
SET total_points         = total_points + $1::numeric,
    last_submission_date = $2::date,
    updated_at           = NOW()
WHERE user_challenge_id  = $3::uuid
RETURNING id, user_challenge_id, total_points, total_fines, last_submission_date, updated_at
`

type AddChallengeScorePointsParams struct {
	Amount          pgtype.Numeric
	Date            pgtype.Date
	UserChallengeID uuid.UUID
}

func (q *Queries) AddChallengeScorePoints(ctx context.Context, arg AddChallengeScorePointsParams) (ChallengeScore, error) {
	row := q.db.QueryRow(ctx, addChallengeScorePoints, arg.Amount, arg.Date, arg.UserChallengeID)
	var i ChallengeScore
	err := row.Scan(
		&i.ID,
		&i.UserChallengeID,
		&i.TotalPoints,
		&i.TotalFines,
		&i.LastSubmissionDate,
		&i.UpdatedAt,
	)
	return i, err
}

const createChallengeScore = `-- name: CreateChallengeScore :one
INSERT INTO challenge_scores (user_challenge_id)
VALUES ($1)
RETURNING id, user_challenge_id, total_points, total_fines, last_submission_date, updated_at
`

func (q *Queries) CreateChallengeScore(ctx context.Context, userChallengeID uuid.UUID) (ChallengeScore, error) {
	row := q.db.QueryRow(ctx, createChallengeScore, userChallengeID)
	var i ChallengeScore
	err := row.Scan(
		&i.ID,
		&i.UserChallengeID,
		&i.TotalPoints,
		&i.TotalFines,
		&i.LastSubmissionDate,
		&i.UpdatedAt,
	)
	return i, err
}
