// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: challenges.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createChallenge = `-- name: CreateChallenge :one
INSERT INTO challenges (name, description, invite_code, status, start_date, end_date, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, description, invite_code, status, start_date, end_date, created_by, created_at, updated_at
`

type CreateChallengeParams struct {
	Name        string
	Description *string
	InviteCode  string
	Status      ChallengeStatus
	StartDate   pgtype.Date
	EndDate     pgtype.Date
	CreatedBy   uuid.UUID
}

func (q *Queries) CreateChallenge(ctx context.Context, arg CreateChallengeParams) (Challenge, error) {
	row := q.db.QueryRow(ctx, createChallenge,
		arg.Name,
		arg.Description,
		arg.InviteCode,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
		arg.CreatedBy,
	)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.InviteCode,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChallengeByID = `-- name: GetChallengeByID :one
SELECT id, name, description, invite_code, status, start_date, end_date, created_by, created_at, updated_at FROM challenges WHERE id = $1
`

func (q *Queries) GetChallengeByID(ctx context.Context, id uuid.UUID) (Challenge, error) {
	row := q.db.QueryRow(ctx, getChallengeByID, id)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.InviteCode,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChallengeByInviteCode = `-- name: GetChallengeByInviteCode :one
SELECT id, name, description, invite_code, status, start_date, end_date, created_by, created_at, updated_at FROM challenges WHERE invite_code = $1
`

func (q *Queries) GetChallengeByInviteCode(ctx context.Context, inviteCode string) (Challenge, error) {
	row := q.db.QueryRow(ctx, getChallengeByInviteCode, inviteCode)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.InviteCode,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChallengeLeaderboard = `-- name: GetChallengeLeaderboard :many
SELECT
    u.id           AS user_id,
    u.display_name,
    cs.total_points,
    cs.total_fines,
    cs.last_submission_date,
    RANK() OVER (ORDER BY cs.total_points DESC, cs.total_fines ASC)::bigint AS rank
FROM challenge_scores cs
JOIN user_challenges uc ON cs.user_challenge_id = uc.id
JOIN users u             ON uc.user_id = u.id
WHERE uc.challenge_id = $1::uuid
  AND uc.status = 'active'
ORDER BY rank
`

type GetChallengeLeaderboardRow struct {
	UserID             uuid.UUID
	DisplayName        string
	TotalPoints        pgtype.Numeric
	TotalFines         pgtype.Numeric
	LastSubmissionDate pgtype.Date
	Rank               int64
}

func (q *Queries) GetChallengeLeaderboard(ctx context.Context, challengeID uuid.UUID) ([]GetChallengeLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, getChallengeLeaderboard, challengeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChallengeLeaderboardRow
	for rows.Next() {
		var i GetChallengeLeaderboardRow
		if err := rows.Scan(
			&i.UserID,
			&i.DisplayName,
			&i.TotalPoints,
			&i.TotalFines,
			&i.LastSubmissionDate,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserChallenges = `-- name: ListUserChallenges :many
SELECT
    c.id, c.name, c.description, c.invite_code, c.status,
    c.start_date, c.end_date, c.created_by, c.created_at, c.updated_at,
    uc.id        AS uc_id,
    uc.role      AS uc_role,
    uc.status    AS uc_status,
    uc.joined_at AS uc_joined_at
FROM challenges c
JOIN user_challenges uc ON c.id = uc.challenge_id
WHERE uc.user_id = $1 AND uc.status = 'active'
ORDER BY c.created_at DESC
`

type ListUserChallengesRow struct {
	ID          uuid.UUID
	Name        string
	Description *string
	InviteCode  string
	Status      ChallengeStatus
	StartDate   pgtype.Date
	EndDate     pgtype.Date
	CreatedBy   uuid.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	UcID        uuid.UUID
	UcRole      UserChallengeRole
	UcStatus    UserChallengeStatus
	UcJoinedAt  pgtype.Timestamptz
}

func (q *Queries) ListUserChallenges(ctx context.Context, userID uuid.UUID) ([]ListUserChallengesRow, error) {
	rows, err := q.db.Query(ctx, listUserChallenges, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserChallengesRow
	for rows.Next() {
		var i ListUserChallengesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.InviteCode,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UcID,
			&i.UcRole,
			&i.UcStatus,
			&i.UcJoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChallengeStatus = `-- name: UpdateChallengeStatus :one
UPDATE challenges
SET status     = $1::challenge_status,
    updated_at = NOW()
WHERE id       = $2::uuid
RETURNING id, name, description, invite_code, status, start_date, end_date, created_by, created_at, updated_at
`

type UpdateChallengeStatusParams struct {
	Status ChallengeStatus
	ID     uuid.UUID
}

func (q *Queries) UpdateChallengeStatus(ctx context.Context, arg UpdateChallengeStatusParams) (Challenge, error) {
	row := q.db.QueryRow(ctx, updateChallengeStatus, arg.Status, arg.ID)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.InviteCode,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
