// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: challenge_metrics.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createChallengeMetric = `-- name: CreateChallengeMetric :one
INSERT INTO challenge_metrics (challenge_id, metric_id, metric_type, target_value, points, fine_amount)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, challenge_id, metric_id, metric_type, target_value, points, fine_amount, created_at
`

type CreateChallengeMetricParams struct {
	ChallengeID uuid.UUID
	MetricID    uuid.UUID
	MetricType  MetricType
	TargetValue pgtype.Numeric
	Points      pgtype.Numeric
	FineAmount  pgtype.Numeric
}

func (q *Queries) CreateChallengeMetric(ctx context.Context, arg CreateChallengeMetricParams) (ChallengeMetric, error) {
	row := q.db.QueryRow(ctx, createChallengeMetric,
		arg.ChallengeID,
		arg.MetricID,
		arg.MetricType,
		arg.TargetValue,
		arg.Points,
		arg.FineAmount,
	)
	var i ChallengeMetric
	err := row.Scan(
		&i.ID,
		&i.ChallengeID,
		&i.MetricID,
		&i.MetricType,
		&i.TargetValue,
		&i.Points,
		&i.FineAmount,
		&i.CreatedAt,
	)
	return i, err
}

const listChallengeMetrics = `-- name: ListChallengeMetrics :many
SELECT
    cm.id, cm.challenge_id, cm.metric_id, cm.metric_type,
    cm.target_value, cm.points, cm.fine_amount, cm.created_at,
    m.name AS metric_name,
    m.unit AS metric_unit
FROM challenge_metrics cm
JOIN metrics m ON cm.metric_id = m.id
WHERE cm.challenge_id = $1
ORDER BY cm.created_at
`

type ListChallengeMetricsRow struct {
	ID          uuid.UUID
	ChallengeID uuid.UUID
	MetricID    uuid.UUID
	MetricType  MetricType
	TargetValue pgtype.Numeric
	Points      pgtype.Numeric
	FineAmount  pgtype.Numeric
	CreatedAt   pgtype.Timestamptz
	MetricName  string
	MetricUnit  string
}

func (q *Queries) ListChallengeMetrics(ctx context.Context, challengeID uuid.UUID) ([]ListChallengeMetricsRow, error) {
	rows, err := q.db.Query(ctx, listChallengeMetrics, challengeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChallengeMetricsRow
	for rows.Next() {
		var i ListChallengeMetricsRow
		if err := rows.Scan(
			&i.ID,
			&i.ChallengeID,
			&i.MetricID,
			&i.MetricType,
			&i.TargetValue,
			&i.Points,
			&i.FineAmount,
			&i.CreatedAt,
			&i.MetricName,
			&i.MetricUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
