// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: daily_submissions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDailySubmission = `-- name: CreateDailySubmission :one
INSERT INTO daily_submissions (user_challenge_id, date, submission_type)
VALUES ($1, $2, $3)
RETURNING id, user_challenge_id, date, submission_type, submitted_at
`

type CreateDailySubmissionParams struct {
	UserChallengeID uuid.UUID
	Date            pgtype.Date
	SubmissionType  SubmissionType
}

func (q *Queries) CreateDailySubmission(ctx context.Context, arg CreateDailySubmissionParams) (DailySubmission, error) {
	row := q.db.QueryRow(ctx, createDailySubmission, arg.UserChallengeID, arg.Date, arg.SubmissionType)
	var i DailySubmission
	err := row.Scan(
		&i.ID,
		&i.UserChallengeID,
		&i.Date,
		&i.SubmissionType,
		&i.SubmittedAt,
	)
	return i, err
}

const listMembersWithoutSubmission = `-- name: ListMembersWithoutSubmission :many
SELECT
    uc.id                            AS user_challenge_id,
    COALESCE(SUM(cm.fine_amount), 0) AS total_fine
FROM user_challenges uc
JOIN challenges c              ON uc.challenge_id = c.id
LEFT JOIN challenge_metrics cm ON cm.challenge_id  = uc.challenge_id
WHERE uc.status = 'active'
  AND c.status  = 'active'
  AND NOT EXISTS (
      SELECT 1 FROM daily_submissions ds
      WHERE ds.user_challenge_id = uc.id
        AND ds.date = $1::date
  )
GROUP BY uc.id
`

type ListMembersWithoutSubmissionRow struct {
	UserChallengeID uuid.UUID
	TotalFine       interface{}
}

func (q *Queries) ListMembersWithoutSubmission(ctx context.Context, date pgtype.Date) ([]ListMembersWithoutSubmissionRow, error) {
	rows, err := q.db.Query(ctx, listMembersWithoutSubmission, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersWithoutSubmissionRow
	for rows.Next() {
		var i ListMembersWithoutSubmissionRow
		if err := rows.Scan(&i.UserChallengeID, &i.TotalFine); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSubmissions = `-- name: ListUserSubmissions :many
SELECT id, user_challenge_id, date, submission_type, submitted_at
FROM daily_submissions
WHERE user_challenge_id = $1::uuid
ORDER BY date DESC
`

func (q *Queries) ListUserSubmissions(ctx context.Context, userChallengeID uuid.UUID) ([]DailySubmission, error) {
	rows, err := q.db.Query(ctx, listUserSubmissions, userChallengeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailySubmission
	for rows.Next() {
		var i DailySubmission
		if err := rows.Scan(
			&i.ID,
			&i.UserChallengeID,
			&i.Date,
			&i.SubmissionType,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
