// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_verification_tokens.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailVerificationToken = `-- name: CreateEmailVerificationToken :one
INSERT INTO email_verification_tokens (user_id, code, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, code, expires_at, used_at, created_at
`

type CreateEmailVerificationTokenParams struct {
	UserID    uuid.UUID
	Code      string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, createEmailVerificationToken, arg.UserID, arg.Code, arg.ExpiresAt)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUserTokens = `-- name: DeleteUserTokens :exec
DELETE FROM email_verification_tokens
WHERE user_id = $1
`

func (q *Queries) DeleteUserTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserTokens, userID)
	return err
}

const getLatestTokenForUser = `-- name: GetLatestTokenForUser :one
SELECT id, user_id, code, expires_at, used_at, created_at FROM email_verification_tokens
WHERE user_id  = $1
  AND used_at  IS NULL
  AND expires_at > NOW()
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestTokenForUser(ctx context.Context, userID uuid.UUID) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, getLatestTokenForUser, userID)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markTokenUsed = `-- name: MarkTokenUsed :exec
UPDATE email_verification_tokens
SET used_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkTokenUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markTokenUsed, id)
	return err
}
