// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metrics.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getMetricByID = `-- name: GetMetricByID :one
SELECT id, name, unit, description, created_at FROM metrics WHERE id = $1
`

func (q *Queries) GetMetricByID(ctx context.Context, id uuid.UUID) (Metric, error) {
	row := q.db.QueryRow(ctx, getMetricByID, id)
	var i Metric
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Unit,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listMetrics = `-- name: ListMetrics :many
SELECT id, name, unit, description, created_at FROM metrics ORDER BY name
`

func (q *Queries) ListMetrics(ctx context.Context) ([]Metric, error) {
	rows, err := q.db.Query(ctx, listMetrics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Metric
	for rows.Next() {
		var i Metric
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Unit,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
