// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ChallengeStatus string

const (
	ChallengeStatusDraft     ChallengeStatus = "draft"
	ChallengeStatusActive    ChallengeStatus = "active"
	ChallengeStatusCompleted ChallengeStatus = "completed"
	ChallengeStatusCancelled ChallengeStatus = "cancelled"
)

func (e *ChallengeStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChallengeStatus(s)
	case string:
		*e = ChallengeStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ChallengeStatus: %T", src)
	}
	return nil
}

type NullChallengeStatus struct {
	ChallengeStatus ChallengeStatus
	Valid           bool // Valid is true if ChallengeStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChallengeStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ChallengeStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChallengeStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChallengeStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChallengeStatus), nil
}

type MetricType string

const (
	MetricTypeMin MetricType = "min"
	MetricTypeMax MetricType = "max"
)

func (e *MetricType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MetricType(s)
	case string:
		*e = MetricType(s)
	default:
		return fmt.Errorf("unsupported scan type for MetricType: %T", src)
	}
	return nil
}

type NullMetricType struct {
	MetricType MetricType
	Valid      bool // Valid is true if MetricType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMetricType) Scan(value interface{}) error {
	if value == nil {
		ns.MetricType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MetricType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMetricType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MetricType), nil
}

type SubmissionType string

const (
	SubmissionTypeSubmitted SubmissionType = "submitted"
	SubmissionTypeMissed    SubmissionType = "missed"
)

func (e *SubmissionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubmissionType(s)
	case string:
		*e = SubmissionType(s)
	default:
		return fmt.Errorf("unsupported scan type for SubmissionType: %T", src)
	}
	return nil
}

type NullSubmissionType struct {
	SubmissionType SubmissionType
	Valid          bool // Valid is true if SubmissionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubmissionType) Scan(value interface{}) error {
	if value == nil {
		ns.SubmissionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubmissionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubmissionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubmissionType), nil
}

type UserChallengeRole string

const (
	UserChallengeRoleHost        UserChallengeRole = "host"
	UserChallengeRoleCohost      UserChallengeRole = "cohost"
	UserChallengeRoleParticipant UserChallengeRole = "participant"
)

func (e *UserChallengeRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserChallengeRole(s)
	case string:
		*e = UserChallengeRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserChallengeRole: %T", src)
	}
	return nil
}

type NullUserChallengeRole struct {
	UserChallengeRole UserChallengeRole
	Valid             bool // Valid is true if UserChallengeRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserChallengeRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserChallengeRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserChallengeRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserChallengeRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserChallengeRole), nil
}

type UserChallengeStatus string

const (
	UserChallengeStatusActive UserChallengeStatus = "active"
	UserChallengeStatusLeft   UserChallengeStatus = "left"
)

func (e *UserChallengeStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserChallengeStatus(s)
	case string:
		*e = UserChallengeStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserChallengeStatus: %T", src)
	}
	return nil
}

type NullUserChallengeStatus struct {
	UserChallengeStatus UserChallengeStatus
	Valid               bool // Valid is true if UserChallengeStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserChallengeStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserChallengeStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserChallengeStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserChallengeStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserChallengeStatus), nil
}

type Challenge struct {
	ID          uuid.UUID
	Name        string
	Description *string
	InviteCode  string
	Status      ChallengeStatus
	StartDate   pgtype.Date
	EndDate     pgtype.Date
	CreatedBy   uuid.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ChallengeMetric struct {
	ID          uuid.UUID
	ChallengeID uuid.UUID
	MetricID    uuid.UUID
	MetricType  MetricType
	TargetValue pgtype.Numeric
	Points      pgtype.Numeric
	FineAmount  pgtype.Numeric
	CreatedAt   pgtype.Timestamptz
}

type ChallengeScore struct {
	ID                 uuid.UUID
	UserChallengeID    uuid.UUID
	TotalPoints        pgtype.Numeric
	TotalFines         pgtype.Numeric
	LastSubmissionDate pgtype.Date
	UpdatedAt          pgtype.Timestamptz
}

type DailySubmission struct {
	ID              uuid.UUID
	UserChallengeID uuid.UUID
	Date            pgtype.Date
	SubmissionType  SubmissionType
	SubmittedAt     pgtype.Timestamptz
	MediaKey        *string
}

type EmailVerificationToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Code      string
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Metric struct {
	ID          uuid.UUID
	Name        string
	Unit        string
	Description *string
	CreatedAt   pgtype.Timestamptz
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	DeviceID  string
	IpAddress *string
	UserAgent *string
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type SubmissionMetricValue struct {
	ID            uuid.UUID
	SubmissionID  uuid.UUID
	MetricID      uuid.UUID
	Value         pgtype.Numeric
	Passed        bool
	PointsAwarded pgtype.Numeric
	CreatedAt     pgtype.Timestamptz
}

type User struct {
	ID            uuid.UUID
	Email         string
	PasswordHash  *string
	DisplayName   string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	GoogleID      *string
	EmailVerified bool
}

type UserChallenge struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	ChallengeID uuid.UUID
	Role        UserChallengeRole
	Status      UserChallengeStatus
	JoinedAt    pgtype.Timestamptz
}
