// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: submission_media.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countSubmissionMedia = `-- name: CountSubmissionMedia :one
SELECT COUNT(*) FROM submission_media WHERE submission_id = $1
`

func (q *Queries) CountSubmissionMedia(ctx context.Context, submissionID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSubmissionMedia, submissionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSubmissionMedia = `-- name: CreateSubmissionMedia :one
INSERT INTO submission_media (submission_id, media_key)
VALUES ($1, $2)
RETURNING id, submission_id, media_key, created_at
`

type CreateSubmissionMediaParams struct {
	SubmissionID uuid.UUID
	MediaKey     string
}

func (q *Queries) CreateSubmissionMedia(ctx context.Context, arg CreateSubmissionMediaParams) (SubmissionMedium, error) {
	row := q.db.QueryRow(ctx, createSubmissionMedia, arg.SubmissionID, arg.MediaKey)
	var i SubmissionMedium
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.MediaKey,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredSubmissionMedia = `-- name: DeleteExpiredSubmissionMedia :exec
DELETE FROM submission_media WHERE created_at < $1
`

func (q *Queries) DeleteExpiredSubmissionMedia(ctx context.Context, createdAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteExpiredSubmissionMedia, createdAt)
	return err
}

const listChallengeFeed = `-- name: ListChallengeFeed :many
SELECT ds.id AS submission_id, u.id AS user_id, u.display_name, ds.date, sm.media_key
FROM submission_media sm
JOIN daily_submissions ds ON ds.id = sm.submission_id
JOIN user_challenges uc   ON uc.id = ds.user_challenge_id
JOIN users u              ON u.id  = uc.user_id
WHERE uc.challenge_id = $1
  AND sm.created_at >= NOW() - INTERVAL '7 days'
ORDER BY ds.date DESC, u.display_name, sm.created_at
`

type ListChallengeFeedRow struct {
	SubmissionID uuid.UUID
	UserID       uuid.UUID
	DisplayName  string
	Date         pgtype.Date
	MediaKey     string
}

func (q *Queries) ListChallengeFeed(ctx context.Context, challengeID uuid.UUID) ([]ListChallengeFeedRow, error) {
	rows, err := q.db.Query(ctx, listChallengeFeed, challengeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChallengeFeedRow
	for rows.Next() {
		var i ListChallengeFeedRow
		if err := rows.Scan(
			&i.SubmissionID,
			&i.UserID,
			&i.DisplayName,
			&i.Date,
			&i.MediaKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredSubmissionMedia = `-- name: ListExpiredSubmissionMedia :many
SELECT id, media_key FROM submission_media WHERE created_at < $1
`

type ListExpiredSubmissionMediaRow struct {
	ID       uuid.UUID
	MediaKey string
}

func (q *Queries) ListExpiredSubmissionMedia(ctx context.Context, createdAt pgtype.Timestamptz) ([]ListExpiredSubmissionMediaRow, error) {
	rows, err := q.db.Query(ctx, listExpiredSubmissionMedia, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiredSubmissionMediaRow
	for rows.Next() {
		var i ListExpiredSubmissionMediaRow
		if err := rows.Scan(&i.ID, &i.MediaKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaKeysByChallenge = `-- name: ListMediaKeysByChallenge :many
SELECT sm.media_key
FROM submission_media sm
JOIN daily_submissions ds ON ds.id = sm.submission_id
JOIN user_challenges uc   ON uc.id = ds.user_challenge_id
WHERE uc.challenge_id = $1
`

func (q *Queries) ListMediaKeysByChallenge(ctx context.Context, challengeID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listMediaKeysByChallenge, challengeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var media_key string
		if err := rows.Scan(&media_key); err != nil {
			return nil, err
		}
		items = append(items, media_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissionMediaBySubmissions = `-- name: ListSubmissionMediaBySubmissions :many
SELECT id, submission_id, media_key, created_at
FROM submission_media
WHERE submission_id = ANY($1::uuid[])
ORDER BY created_at
`

func (q *Queries) ListSubmissionMediaBySubmissions(ctx context.Context, dollar_1 []uuid.UUID) ([]SubmissionMedium, error) {
	rows, err := q.db.Query(ctx, listSubmissionMediaBySubmissions, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubmissionMedium
	for rows.Next() {
		var i SubmissionMedium
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.MediaKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmittedWithoutMedia = `-- name: ListSubmittedWithoutMedia :many
SELECT ds.id, ds.user_challenge_id, c.media_fine_amount
FROM daily_submissions ds
JOIN user_challenges uc ON uc.id = ds.user_challenge_id
JOIN challenges c        ON c.id  = uc.challenge_id
WHERE ds.date           = $1
  AND ds.submission_type = 'submitted'
  AND ds.media_fine_applied_at IS NULL
  AND c.status           = 'active'
  AND c.media_required   = true
  AND NOT EXISTS (
    SELECT 1 FROM submission_media sm WHERE sm.submission_id = ds.id
  )
`

type ListSubmittedWithoutMediaRow struct {
	ID              uuid.UUID
	UserChallengeID uuid.UUID
	MediaFineAmount pgtype.Numeric
}

func (q *Queries) ListSubmittedWithoutMedia(ctx context.Context, date pgtype.Date) ([]ListSubmittedWithoutMediaRow, error) {
	rows, err := q.db.Query(ctx, listSubmittedWithoutMedia, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubmittedWithoutMediaRow
	for rows.Next() {
		var i ListSubmittedWithoutMediaRow
		if err := rows.Scan(&i.ID, &i.UserChallengeID, &i.MediaFineAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMediaFineApplied = `-- name: MarkMediaFineApplied :exec
UPDATE daily_submissions
SET media_fine_applied_at = NOW()
WHERE id = $1
  AND media_fine_applied_at IS NULL
`

func (q *Queries) MarkMediaFineApplied(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markMediaFineApplied, id)
	return err
}
