// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: submission_metric_values.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSubmissionMetricValue = `-- name: CreateSubmissionMetricValue :one
INSERT INTO submission_metric_values (submission_id, metric_id, value, passed, points_awarded)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, submission_id, metric_id, value, passed, points_awarded, created_at
`

type CreateSubmissionMetricValueParams struct {
	SubmissionID  uuid.UUID
	MetricID      uuid.UUID
	Value         pgtype.Numeric
	Passed        bool
	PointsAwarded pgtype.Numeric
}

func (q *Queries) CreateSubmissionMetricValue(ctx context.Context, arg CreateSubmissionMetricValueParams) (SubmissionMetricValue, error) {
	row := q.db.QueryRow(ctx, createSubmissionMetricValue,
		arg.SubmissionID,
		arg.MetricID,
		arg.Value,
		arg.Passed,
		arg.PointsAwarded,
	)
	var i SubmissionMetricValue
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.MetricID,
		&i.Value,
		&i.Passed,
		&i.PointsAwarded,
		&i.CreatedAt,
	)
	return i, err
}

const listMetricValuesBySubmissions = `-- name: ListMetricValuesBySubmissions :many
SELECT
    smv.id, smv.submission_id, smv.metric_id,
    smv.value, smv.passed, smv.points_awarded, smv.created_at,
    m.name AS metric_name
FROM submission_metric_values smv
JOIN metrics m ON m.id = smv.metric_id
WHERE smv.submission_id = ANY($1::uuid[])
ORDER BY smv.submission_id, smv.created_at
`

type ListMetricValuesBySubmissionsRow struct {
	ID            uuid.UUID
	SubmissionID  uuid.UUID
	MetricID      uuid.UUID
	Value         pgtype.Numeric
	Passed        bool
	PointsAwarded pgtype.Numeric
	CreatedAt     pgtype.Timestamptz
	MetricName    string
}

func (q *Queries) ListMetricValuesBySubmissions(ctx context.Context, submissionIds []uuid.UUID) ([]ListMetricValuesBySubmissionsRow, error) {
	rows, err := q.db.Query(ctx, listMetricValuesBySubmissions, submissionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMetricValuesBySubmissionsRow
	for rows.Next() {
		var i ListMetricValuesBySubmissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.MetricID,
			&i.Value,
			&i.Passed,
			&i.PointsAwarded,
			&i.CreatedAt,
			&i.MetricName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
