// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, display_name)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, display_name, created_at, updated_at, google_id, email_verified
`

type CreateUserParams struct {
	Email        string
	PasswordHash *string
	DisplayName  string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleID,
		&i.EmailVerified,
	)
	return i, err
}

const createUserOAuth = `-- name: CreateUserOAuth :one
INSERT INTO users (email, display_name, google_id, email_verified)
VALUES ($1, $2, $3, TRUE)
RETURNING id, email, password_hash, display_name, created_at, updated_at, google_id, email_verified
`

type CreateUserOAuthParams struct {
	Email       string
	DisplayName string
	GoogleID    *string
}

func (q *Queries) CreateUserOAuth(ctx context.Context, arg CreateUserOAuthParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserOAuth, arg.Email, arg.DisplayName, arg.GoogleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleID,
		&i.EmailVerified,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, display_name, created_at, updated_at, google_id, email_verified FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleID,
		&i.EmailVerified,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, email, password_hash, display_name, created_at, updated_at, google_id, email_verified FROM users WHERE google_id = $1 LIMIT 1
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleID,
		&i.EmailVerified,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, display_name, created_at, updated_at, google_id, email_verified FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleID,
		&i.EmailVerified,
	)
	return i, err
}

const getUserStats = `-- name: GetUserStats :one
SELECT
    COUNT(DISTINCT uc.id)::bigint                                        AS challenges_joined,
    COALESCE(SUM(cs.total_points), 0)::numeric                           AS total_points,
    COALESCE(SUM(cs.total_fines),  0)::numeric                           AS total_fines,
    COUNT(ds.id) FILTER (WHERE ds.submission_type = 'submitted')::bigint AS total_submissions,
    COUNT(ds.id) FILTER (WHERE ds.submission_type = 'missed')::bigint    AS missed_submissions
FROM user_challenges uc
LEFT JOIN challenge_scores  cs ON cs.user_challenge_id = uc.id
LEFT JOIN daily_submissions ds ON ds.user_challenge_id = uc.id
WHERE uc.user_id = $1::uuid
  AND uc.status  = 'active'
`

type GetUserStatsRow struct {
	ChallengesJoined  int64
	TotalPoints       pgtype.Numeric
	TotalFines        pgtype.Numeric
	TotalSubmissions  int64
	MissedSubmissions int64
}

func (q *Queries) GetUserStats(ctx context.Context, userID uuid.UUID) (GetUserStatsRow, error) {
	row := q.db.QueryRow(ctx, getUserStats, userID)
	var i GetUserStatsRow
	err := row.Scan(
		&i.ChallengesJoined,
		&i.TotalPoints,
		&i.TotalFines,
		&i.TotalSubmissions,
		&i.MissedSubmissions,
	)
	return i, err
}

const setEmailVerified = `-- name: SetEmailVerified :exec
UPDATE users
SET email_verified = TRUE,
    updated_at     = NOW()
WHERE id = $1
`

func (q *Queries) SetEmailVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setEmailVerified, id)
	return err
}

const updateUserGoogleID = `-- name: UpdateUserGoogleID :one
UPDATE users
SET google_id  = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, display_name, created_at, updated_at, google_id, email_verified
`

type UpdateUserGoogleIDParams struct {
	ID       uuid.UUID
	GoogleID *string
}

func (q *Queries) UpdateUserGoogleID(ctx context.Context, arg UpdateUserGoogleIDParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserGoogleID, arg.ID, arg.GoogleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleID,
		&i.EmailVerified,
	)
	return i, err
}
