// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_challenges.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUserChallenge = `-- name: CreateUserChallenge :one
INSERT INTO user_challenges (user_id, challenge_id, role)
VALUES ($1, $2, $3)
RETURNING id, user_id, challenge_id, role, status, joined_at
`

type CreateUserChallengeParams struct {
	UserID      uuid.UUID
	ChallengeID uuid.UUID
	Role        UserChallengeRole
}

func (q *Queries) CreateUserChallenge(ctx context.Context, arg CreateUserChallengeParams) (UserChallenge, error) {
	row := q.db.QueryRow(ctx, createUserChallenge, arg.UserID, arg.ChallengeID, arg.Role)
	var i UserChallenge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChallengeID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
	)
	return i, err
}

const getUserChallenge = `-- name: GetUserChallenge :one
SELECT id, user_id, challenge_id, role, status, joined_at FROM user_challenges
WHERE user_id = $1 AND challenge_id = $2
`

type GetUserChallengeParams struct {
	UserID      uuid.UUID
	ChallengeID uuid.UUID
}

func (q *Queries) GetUserChallenge(ctx context.Context, arg GetUserChallengeParams) (UserChallenge, error) {
	row := q.db.QueryRow(ctx, getUserChallenge, arg.UserID, arg.ChallengeID)
	var i UserChallenge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChallengeID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
	)
	return i, err
}

const leaveChallenge = `-- name: LeaveChallenge :one
UPDATE user_challenges
SET status = 'left'
WHERE user_id      = $1::uuid
  AND challenge_id = $2::uuid
RETURNING id, user_id, challenge_id, role, status, joined_at
`

type LeaveChallengeParams struct {
	UserID      uuid.UUID
	ChallengeID uuid.UUID
}

func (q *Queries) LeaveChallenge(ctx context.Context, arg LeaveChallengeParams) (UserChallenge, error) {
	row := q.db.QueryRow(ctx, leaveChallenge, arg.UserID, arg.ChallengeID)
	var i UserChallenge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChallengeID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
	)
	return i, err
}
